[package]
name = "zeloxy"
version = "0.2.2"
edition = "2024"
license = "MIT"
description = "A library for creating lightweight, asynchronous, and lag-free proxy connections."
repository = "https://github.com/nullclyze/zeloxy"
documentation = "https://docs.rs/zeloxy"
readme = "README.md"
keywords = ["proxy", "http", "socks", "async"]
categories = ["network-programming", "asynchronous"]

[features]
http = []
socks4 = []
socks5 = []
chain = []
stream = []
tools = []
default = ["http", "socks4", "socks5"]
all = ["http", "socks4", "socks5", "chain", "stream", "tools"]

[dependencies]
base64 = "0.22.1"
bytes = "1.11.1"
hashbrown = "0.17.0"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.149"
tokio = { version = "1.52.2", features = ["net", "io-util", "time", "sync", "rt"] }

[dev-dependencies]
zeloxy = { path = ".", features = ["all"] }
tokio = { version = "1.52.2", features = ["macros", "rt-multi-thread"] }